export const GET_INVOICES_START = 'GET_INVOICES_START';
export const GET_INVOICES = 'GET_INVOICES';
export const GET_INVOICES_ERROR = 'GET_INVOICES_ERROR';

export const REFRESH_INVOICES_START = 'REFRESH_INVOICES_START';
export const REFRESH_INVOICES = 'REFRESH_INVOICES';
export const REFRESH_INVOICES_ERROR = 'REFRESH_INVOICES_ERROR';
