export const ADD_INVOICE_START = 'ADD_INVOICE_START';
export const ADD_INVOICE = 'ADD_INVOICE';
export const ADD_INVOICE_ERROR = 'ADD_INVOICE_ERROR';

export const EDIT_INVOICE_START = 'EDIT_INVOICE_START';
export const EDIT_INVOICE = 'EDIT_INVOICE';
export const EDIT_INVOICE_ERROR = 'EDIT_INVOICE_ERROR';

export const DELETE_INVOICE_START = 'DELETE_INVOICE_START';
export const DELETE_INVOICE = 'DELETE_INVOICE';
export const DELETE_INVOICE_ERROR = 'DELETE_INVOICE_ERROR';

export const GET_INVOICE_START = 'GET_INVOICE_START';
export const GET_INVOICE = 'GET_INVOICE';
export const GET_INVOICE_ERROR = 'GET_INVOICE_ERROR';
