export const GET_ACCOUNTS_START = 'GET_ACCOUNTS_START';
export const GET_ACCOUNTS = 'GET_ACCOUNTS';
export const GET_ACCOUNTS_ERROR = 'GET_ACCOUNTS_ERROR';

export const REFRESH_ACCOUNTS_START = 'REFRESH_ACCOUNTS_START';
export const REFRESH_ACCOUNTS = 'REFRESH_ACCOUNTS';
export const REFRESH_ACCOUNTS_ERROR = 'REFRESH_ACCOUNTS_ERROR';
