const SCREENS = {
  DASHBOARD: 'DASHBOARD',
  LOGIN: 'LOGIN',
  ACCOUNT_SELECT: 'ACCOUNT_SELECT',
  LOADING: 'LOADING',
  SETTINGS: 'SETTINGS',
  CLIENTS: 'CLIENTS',
  INVOICES: 'INVOICES',
};

export default SCREENS;
