import hexToRgba from 'hex-to-rgba';

const DEFAULT_COLORS = {
  BLACK: '#000000',
  DARK_BLUE: '#252631',
  BLUE: '#26408B',
  PURPLE: '#86BBD8',
  GREY_2: '#778CA2',
  GREY: '#98A9BC',
  LIGHT_GREY: '#E8ECEF',
  LIGHT_GREY_2: '#F8FAFB',
  LIGHT_GREY_3: '#ecf1f4',
  WHITE: '#FFFFFF',
  RED: '#f10000',
};

const COLORS = {
  ...DEFAULT_COLORS,
  PRIMARY: DEFAULT_COLORS.BLUE,
  DANGER: DEFAULT_COLORS.RED,
  DARK_TEXT: DEFAULT_COLORS.DARK_BLUE,
  LIGHT_TEXT: DEFAULT_COLORS.WHITE,
  DARK_BORDER: DEFAULT_COLORS.LIGHT_GREY,
  LIGHT_BORDER: hexToRgba(DEFAULT_COLORS.WHITE, 0.3),
  LIGHT_PLACEHOLDER: DEFAULT_COLORS.GREY,
  DARK_PLACEHOLDER: DEFAULT_COLORS.GREY,
  BACKGROUND: DEFAULT_COLORS.LIGHT_GREY_2,
};

export default COLORS;
