export const GET_CLIENTS_START = 'GET_CLIENTS_START';
export const GET_CLIENTS = 'GET_CLIENTS';
export const GET_CLIENTS_ERROR = 'GET_CLIENTS_ERROR';

export const REFRESH_CLIENTS_START = 'REFRESH_CLIENTS_START';
export const REFRESH_CLIENTS = 'REFRESH_CLIENTS';
export const REFRESH_CLIENTS_ERROR = 'REFRESH_CLIENTS_ERROR';
