export const ADD_CLIENT_START = 'ADD_CLIENT_START';
export const ADD_CLIENT = 'ADD_CLIENT';
export const ADD_CLIENT_ERROR = 'ADD_CLIENT_ERROR';

export const EDIT_CLIENT_START = 'EDIT_CLIENT_START';
export const EDIT_CLIENT = 'EDIT_CLIENT';
export const EDIT_CLIENT_ERROR = 'EDIT_CLIENT_ERROR';

export const DELETE_CLIENT_START = 'DELETE_CLIENT_START';
export const DELETE_CLIENT = 'DELETE_CLIENT';
export const DELETE_CLIENT_ERROR = 'DELETE_CLIENT_ERROR';

export const GET_CLIENT_START = 'GET_CLIENT_START';
export const GET_CLIENT = 'GET_CLIENT';
export const GET_CLIENT_ERROR = 'GET_CLIENT_ERROR';
